Repository fga-eps-mds/2020.2-Projeto-Kokama-Ensino, pull requests merged in 2021-04, with the labels that each got.

#4 [US11] Cadastrar, editar e remover história do povo kokama
  history/__init__.py
  history/admin.py
  history/apps.py
  history/fixtures/kokama_history.json
  history/forms.py
  history/migrations/__init__.py
  history/models.py
  history/serializers.py
  history/templates/add_history.html
  history/templates/list_history.html
  history/templates/views_history.html
  history/tests.py
  history/urls.py
  history/views.py
  history/views_html.py
  learn/settings.py
  learn/urls.py
  load-seed.py
  static/css/style.css
Labels: 0-MDS, 1-Backend, 3-User story

#3 [US16] Automatic exercises generation
  entrypoint.sh
  exercise/__init__.py
  exercise/admin.py
  exercise/apps.py
  exercise/models.py
  exercise/serializers.py
  exercise/tests.py
  exercise/urls.py
  exercise/views.py
  heroku-entrypoint.sh
  heroku.yml
  history/admin.py
  history/templates/add_history.html
  history/templates/list_history.html
  history/templates/views_history.html
  history/urls.py
  history/views_html.py
  learn/settings.py
  learn/urls.py
  requirements.txt
Labels: 0-MDS, 1-Backend, 3-User story

#5 [HOTFIX] Re-create heroku deploy files that were mistakenly deleted
  heroku-entrypoint.sh
  heroku.yml
Labels: 0-MDS, bug, invalid

#6 [HOTFIX] Fix settings file
  entrypoint.sh
  learn/settings.py
Labels: 0-MDS, bug

#7 Little adjustments to handle options better in frontend
  exercise/views.py
Labels: 0-MDS, 1-Backend
