Repository fga-eps-mds/2020.2-Projeto-Kokama-Ensino, pull requests merged in 2021-05, with the labels that each got.

#11 161 improve learn data security
  exercise/views.py
  learn/env-reference
  learn/urls.py
  story/views.py
Labels: 0-MDS, 1-Backend, 3-Technical Story

#13 164 unit testing in the microservice
  .gitignore
  exercise/apps.py
  exercise/tests.py
  exercise/views.py
  static/css/style.css
  story/tests.py
  tests/__init__.py
  tests/history/__init__.py
  tests/history/test_sample.py
Labels: 0-MDS, 1-Backend

#14 Update README.md
  README.md
  story/tests.py
Labels: 0-MDS, 1-Documentation

#16 Fix tests.py of story app not updated with last story model
  story/tests.py
Labels: 0-MDS, 1-Backend, bug
